---

stages:
  - build
  - test
  - deploy

image: alpine

build_a:
  stage: build
  script:
    - echo "This job build something"

build_b:
  stage: build
  script:
    - echo "This job build something else"

test_a:
  stage: test
  script:
    - echo "This job tests something. It will only run whrn all jobs in the build stage are complete"


test_b:
  stage: test
  script:
    - echo "This job tests something else. It will only run whrn all jobs in the build stage are complete"

deploy_a:
  stage: deploy
  script:
    - echo "This job deploys something"

deploy_b:
  stage: deploy
  script:
    - echo "This job deploys something else"

...
